### PR TITLE
Final UI

### PR DESCRIPTION
**Pull request by malek1038**
Added the UI styling to the missing parts

### CODE REVIEW

**Comment by MadTurt1e** [comment]
Removed crossorigin because it was messing up api calls
Also it seems like the waitingroom feature is now broken, I'll try to fix it

**Comment by malek1038** [comment]
What is broken about the waiting room? It was just working a sec ago

**Comment by MadTurt1e** [comment]
I will see
When starting a game, the players do not load into the list immediately
It might start working if you wait like 10 seconds, but that is not ideal

**Comment by malek1038** [comment]
That's weird, I can't see how css would do that, and I don't think I changed anything in the js file other than adding some divs and class names

**Comment by malek1038** [comment]
If for some reason you can't get it to work, just keep the old waiting room file (which hopefully works) and only add the end of game one.

**Comment by MadTurt1e** [comment]
UseEffect is a little finicky so minor changes could cause something like this to happen

**Comment by MadTurt1e** [comment]
const players = response.data.
setPlayers(players);

It was the removal of these two lines that caused this
I have no idea why this is the case.

**Comment by malek1038** [comment]
Funny enough, I didn't change that part of the file, but when I click to save a file, a plugging I have auto "optimizes" the file, and fixes things like indentation, adds comments, etc. It saw that as being inefficient and tried to fix it, Its funny that this was the reason it broke.

**Comment by MadTurt1e** [comment]
closes #70

**Pull request merged**
