### PR TITLE
Usable buttons

### LINKED ISSUE #9: Lobby and Main Menu
This system is probably to be implemented at the end. 
We want a menu system, where the player can chose which lobby to go into, view statistics, the like. 
In addition, we want a lobby creation system (I am assuming this will be like Amogus), which has a few feature

- High Stakes / Low stakes betting: Players can choose how much the buy in price is. 
- Round Count - 3, 5, or 7. 11 if we're feeling lucky. 
Implementation of high/low stakes betting and round count should be assumed - ie, don't hard code these values. 

This is very much so a UI section, and as such, probably only needs implementation when we learn of UI and the like.

### LINKED ISSUE #14: Alternative Luigi Sprites
Luigi can have a tell, where he acts like he has a good/bad hand
In any case, we should have at least 3 Luigi sprites

- Dealing Luigi
- Staring into your soul Luigi
- Winning Luigi
- Loosing Luigi

### PR DESCRIPTION
**Pull request by MadTurt1e**
Most if not all of the buttons are now usable. The game is not at all featured, but most of the way there. We just need to account for end of round and end of game logic. 
Also, I have taken the liberty of updating our Luigi with a "higher" quality version of Luigi that blends together better - which I believe is basically all we need for Luigi perks. 

I think cosmetics are implementable - Black cards are already in the sprite sheet (used by Luigi), so it shouldn't be too hard to check for the player wins and change this accordingly. 

closes #9, closes #14.

### CODE REVIEW

**Comment by MadTurt1e** [comment]
NOTICE: PicturePokerGame.java had a bug where the connections did not close, and too many open connections broke the program. I've fixed this, but this is something to look out for in future API calls as well.

**Comment by jeffreyw2025** [comment]
This seems good for now. Only slight bug is that when I register a new player, it still shows the page information for the previous player for some reason. I may also add some feedback for if there is an error when registering or logging in.

**Comment by MadTurt1e** [comment]
Give me a second it looks like leaveGame doesn't work quite as I expected I'll fix that right now

**Comment by MadTurt1e** [comment]
Alright both issues have been fixed

**Comment by jeffreyw2025** [comment]
OK, it looks like everything should be functional for now. I'll update you with any suggestions I might want implemented, but I think this is a good starting point.

**Pull request merged**
