### PR TITLE
Crud operations

### LINKED ISSUE #15: End of Game Resolution
At the end of each game we will need to pay out money based on placement. Placement will be determined using the following criteria in order:

- Token Count
- Number of Hands Won
- Player position (P1 > P2 > P3 > P4)

This will probably interact with both the Java and database layer.

### LINKED ISSUE #17: HTTP Operations
Create, Read, Update, and Delete (CRUD)
 HTTP GET/POST/PUT/DELETE operations

This involves a bit of fun html stuff
This must be done for the start of the project

### PR DESCRIPTION
**Pull request by MadTurt1e**
Create, Read, Update, Delete functions complete, but not verified with Postman. 
Please verify functionality before merge - this is really the final necessary feature needed to pass this project, so we better see some functionality. Docker Compose also not verified to work yet. 

Closes #17, implements a baseline version of #9 and #8, closes #15, closes PR #31

### CODE REVIEW

**Comment by jeffreyw2025** [comment]
I've tested some of the functionality using Postman to see how things are running. Here's what I found so far (this is not comprehensive).

- The methods for retrieving player and game information seem to work fine
- The core game method does run to the end successfully, although there are a couple of small issues:
-> The player's roundsWon does not update correctly after winning a round, it remains at 0
-> The players should start with 10 tokens, not 5
-> There should be some initial logic for the buy in to take money from players and form the pot from that (We can deny poor people later)

All in all it does seem to function at least somewhat- we have a decent basis. I'll sure I'll let you know about other stuff down the line today.

**Comment by jeffreyw2025** [comment]
I've finished testing some of the other methods (like the create and delete and join game and stuff) and those seem to be good. Only other thing I would suggest changing is fixing the payout so that it's 100% of the pot minus any rounding errors (right now it's 150%)

**Comment by MadTurt1e** [comment]
I've dealt with all the issues mentioned minus the pot (but ¯\_(ツ)_/¯) and I have also rejected the impoverished. 
Please check for functionality at this stage as well.

**Comment by jeffreyw2025** [comment]
Everything looks good now, will merge into main.

**Pull request merged**
