### PR TITLE
Game details

### PR DESCRIPTION
**Pull request by MadTurt1e**
A game can now be played end-to-end. 
Please bug test and let me know / fix yourself any issues you find. 
If you encounter the React red screen of death, that is an issue we need to fix as well (no matter how you got there). 

#53 - I have added a few backgrounds to be tested: a brighter one, darker one, and standard one. All of them have a blur filter because I think that looks better. Change the filename to luigisCasino.jpg to sample what it would look like in the menu.

### CODE REVIEW

**Comment by jeffreyw2025** [comment]
Ok, I tried out the new end of round screen, and it seems to work reasonably well. A few nitpicks I found:

- On the main menu it seems that the rejoin game button overlaps with the new information. I suggest moving it up a bit.
- I think the interval for the stats to show up should maybe be cut to 10 seconds. In fact, I've decided to cut it for the time being. You can revert it if you think it would be better.
- I feel that the light casino image should be used on the stats menu and end of game screen, while the normal image can stay for the login and main menus. The dark one just doesn't seem to look good.
- I will try to add Luigi's hand info to the end of round stuff, for reference.

**Comment by jeffreyw2025** [comment]
Ok, adding to the list it seems like the Create Game menu is kinda scuffed, and the login screen also remains scuffed.

image

**Comment by MadTurt1e** [comment]
i have reason to believe that your screen is unnaturally low resolution
Well, I've adjusted the images and fonts to be adjustable with screen height, so even the worst of screen resolutions will be able to see the relevant texts.

**Comment by jeffreyw2025** [comment]
You seem to have fixed most of the errors I pointed out. However, I have a couple new and pending suggestions:

- On the sidebar, it would be ideal to track the number of rounds each player won since it acts as a tiebreaker. This also applies to the end of game screen. If it doesn't fit, though, you don't have to add it.
- For some reason, Luigi's hand shows as soon as the player decides to end the round. It would be better to show it during the showdown after all the players change their cards.

I also decided to change things a bit so that the players are ordered by token count in the end of round screen, and it now shows the new token counts as well as the win/loss amounts.

**Comment by MadTurt1e** [comment]
Luigi's hand showing after the player ends the round is intentional - I think this gives the player something to grieve about while waiting for the slower players to finish their turn. Without this, players don't really get a response when they end their turn, other than a little blurb in the bottom left telling them to wait out the round. (this may not really be ideal for when the player ends their turn, but I can't really think of anything better to do)

Round counts do sound like a good idea, I have added that.

**Comment by jeffreyw2025** [comment]
Everything seems mostly good to go on the frontend side- the only thing I have to say at this point is that all the players' info goes off the bottom of the screen on my laptop, but at this point I'm just accepting that we're going to have resolution problems to some extent.

I've made some final adjustments, please double-check to make sure I didn't break anything

**Comment by MadTurt1e** [comment]
okay I think I have avoided most react red screens of death, can merge whenever

**Comment by jeffreyw2025** [comment]
Looks good with most recent test, will merge in now

**Pull request merged**
